### ISSUE TITLE
Sort techniques drop-down

### ISSUE THREAD

**Issue by nitrosx** [panosc-eu/searchui#15]
As a user, when I go and select a technique from the drop-down, I would expect to found them ordered alphabetically.
It would make it easier to find the correct one.

**Comment by axelboc** [comment]
This is already implemented but not yet deployed :+1: - https://github.com/panosc-eu/searchui/blob/main/src/Search/AsyncAutocomplete.js#L12

I will try to work on continuous deployment to GitHub Pages next week.

**Comment by noobadmin** [comment]
Deployed branch new-numeric-param that also includes the sorted techniques.
