### ISSUE TITLE
Query syntax

### ISSUE THREAD

**Issue by nitrosx** [panosc-eu/searchui#16]
I tested the PaNOSC search API and read more attentively the query documentation from loopback.
The correct syntax for the document query when applying conditions on parameters of the related datasets is the following:
```json
{
 "limit" : 10,
 "include" : [
  {
   "relation" : "datasets",
   "scope" : {
    "include" : [
     {
      "relation" : "parameters",
      "scope" : {
       "where" : {
        "and" : [
         { "name" : "sample_temperature"},
         { "value" : { "between" : [0, 0] } }
        ]
       }
      }
     }
    ]
   }
  }
 ]
}
```

**Comment by noobadmin** [comment]
As I did a couple of changes to how parameters are handled on the new branch that link no longer works, I might tweak this later.
https://pan-dev-portal.eli-laser.eu/search/?q=test&incident_wavelength=320~2000%27between
