### ISSUE TITLE
Make DOI look like a LINK

### ISSUE THREAD

**Issue by nitrosx** [panosc-eu/searchui#47]
As a user, I would like to have the DOI of each entry styled as a link, so I know that I can click on it and land on the document page.

**Comment by nitrosx** [comment]
On second thought, I wonder if this is the best solution. Each tile might become a little to heavy, specifically when the tiles are expanded.
I wonder if we can find an alternative and more elegant solution.
Is there any industry standard?

**Comment by axelboc** [comment]
According to accessibility guidelines, it should be visually different from non-clickable text, so usually underlined or bold. In this case, however, the link is not in the middle of a paragraph, so it's less of a problem. However, there are some visual cues that can help, like colour. Perhaps we could use the same blue as for normal links?

Most importantly, there needs to be a visual cue on hover, so in this case, underline would be appropriate. Same goes with the main title link.

**Comment by nitrosx** [comment]
Following your comment, would it be an acceptable solution to  keep the current styling and make the links italics on hover?
Or something similar.

**Comment by axelboc** [comment]
Underline is what people expect on hover. I have no opinion about the unhovered state -- it can stay as is if you like.

**Comment by nitrosx** [comment]
@axelboc Can you check with your boss about this and see what it is his preferred solution?

**Comment by noobadmin** [comment]
I propose I add an "external link" icon to doi, while hovering on either title, doi or icon, doi and icon change color while the title underlines.

**Comment by nitrosx** [comment]
@noobadmin : go ahead!!! Once is deployed, we start collecting user feedback.
Thank you so much
