### ISSUE TITLE
Show data provider when tiles are expanded

### ISSUE THREAD

**Issue by nitrosx** [panosc-eu/searchui#48]
As a user, I would like to be see the facility providing the data when I view the results are expanded.
The facility is currently shown only when the tiles are minimized

**Comment by noobadmin** [comment]
No problem, while we're at it: what else should be shown in the expanded detail?

**Comment by noobadmin** [comment]
I'd like to change the expanded view a bit in the sense that I'd like to expand just one at a time and fetch all "stuff" in one request unlike it is now.
