### ISSUE TITLE
Allow decimals in min-max filters

### ISSUE THREAD

**Issue by nitrosx** [panosc-eu/searchui#55]
As a user, it is important to be able to query results with filter 

> Incident Wavelength  between 2.4 and 2.6 Angstrom

Currently it is not possible to insert decimals in the numeric filters. To be able to use the previous filter, I need to enter it as follow

> Incident Wavelength between 240 and 260 pm

Would it be possible to allow decimals value for the following filters:
- Incident Wavelength
- Incident Photo Energy
- Temperature
- Pressure

**Comment by noobadmin** [comment]
Looks like that didn't quite do it.
