### ISSUE TITLE
Members and roles display

### ISSUE THREAD

**Issue by antolinos** [panosc-eu/searchui#61]
Currently, the portal shows the list of members of a specific investigation. A member is, as far as I understand, a role played by a person with an affiliation within an investigation.

A person can play multiple roles (i.e: Proposer and Participant) within an experiment and this should be somehow captured but the UI otherwise it shows members that are duplicated. 

Example: (https://data.panosc.eu/search/?q=covid)
![image](https://user-images.githubusercontent.com/2901169/195273963-a4a58ded-9041-4bb0-9bb0-ce417af7e441.png)

I'd suggest:
1) Remove duplicates (filter the list of members by uniqueness of `member.person.fullName`)
or
2) Display the role for each member like here:
![image](https://user-images.githubusercontent.com/2901169/195274389-d1678039-e625-4934-a887-2a5ef28bec02.png)

**Comment by andygotz** [comment]
I fully agree with @antolinos. Stupid question - why are users displayed multiple times? Is this an issue with the search api or the ui,?  @nitrosx do you know?

I find the option to display users is too hidden still. There is no indication that by clicking below the abstract that there is more information. Could we have something like "Members" or "Properties" displayed as a clickable link and a tooltip? Maybe this needs a separate issue if it doesn't already exist. This is not the first time I have made this request ;-)

**Comment by antolinos** [comment]
> why are users displayed multiple times? Is this an issue with the search api or the ui,?

This happens because the list of members contains an item for each role. That means that users playing multiple roles will appear multiple times.

I do not think it is a problem with the API or an error on the UI. It needs just to be handled.

Example of data returned by API:
https://federated.panosc.ess.eu/api/documents/436648953?filter=%7B%22include%22%3A%5B%7B%22relation%22%3A%22members%22%2C%22scope%22%3A%7B%22include%22%3A%5B%7B%22relation%22%3A%22affiliation%22%7D%2C%7B%22relation%22%3A%22person%22%7D%5D%7D%7D%5D%2C%22limit%22%3A0%7D

**Comment by nitrosx** [comment]
@andygotz: @antolinos is correct. That's the way the members are returned from facilities through the federated search. 
Easy fix is that we adopt @antolinos suggested display and we add the logic in the portal.
Than we should discuss a long term solution: should we leave it like this or should the facility search api provide the aggregated list? Of course, this last solution will take longer to be fully implemented at all facilities.
